Repository Consensys/gnark, pull requests merged in 2022-07, with the labels that each got.

#320 perf[nonnative]: implement optimisations for field emulation
  std/math/nonnative/composition.go
  std/math/nonnative/doc.go
  std/math/nonnative/hints.go
  std/math/nonnative/variable.go
  std/math/nonnative/variable_test.go
Labels: perf

#334 fix(nonnative): off by one error
  std/math/nonnative/variable.go
Labels: bug

#331 perf: allocate less in test engine
  internal/backend/circuits/div.go
  test/engine.go
Labels: perf

#325 feat: implement API using non-native field emulation
  frontend/compile.go
  std/math/nonnative/api.go
  std/math/nonnative/api_test.go
  std/math/nonnative/hints.go
  std/math/nonnative/variable.go
  std/math/nonnative/variable_test.go
Labels: new feature

#310 Add new BLS24-317
  README.md
  backend/groth16/groth16.go
  backend/plonk/plonk.go
  backend/witness/vector.go
  backend/witness/witness_test.go
  doc.go
  frontend/cs/r1cs/builder.go
  frontend/cs/scs/builder.go
  internal/backend/bls24-317/cs/r1cs.go
  internal/backend/bls24-317/cs/r1cs_sparse.go
  internal/backend/bls24-317/cs/r1cs_test.go
  internal/backend/bls24-317/cs/solution.go
  internal/backend/bls24-317/groth16/groth16_test.go
  internal/backend/bls24-317/groth16/marshal.go
  internal/backend/bls24-317/groth16/marshal_test.go
  internal/backend/bls24-317/groth16/prove.go
  internal/backend/bls24-317/groth16/setup.go
  internal/backend/bls24-317/groth16/verify.go
  internal/backend/bls24-317/plonk/marshal.go
  internal/backend/bls24-317/plonk/marshal_test.go
  internal/backend/bls24-317/plonk/plonk_test.go
  internal/backend/bls24-317/plonk/prove.go
  internal/backend/bls24-317/plonk/setup.go
  internal/backend/bls24-317/plonk/verify.go
  internal/backend/bls24-317/witness/witness.go
  internal/generator/backend/main.go
  internal/stats/latest.stats
  internal/stats/stats.go
  std/algebra/twistededwards/curve_test.go
  std/algebra/twistededwards/twistededwards.go
  std/fiat-shamir/transcript_test.go
  std/hash/mimc/encrypt.go
  std/hash/mimc/mimc_test.go
  std/signature/eddsa/eddsa.go
  std/signature/eddsa/eddsa_test.go
  test/kzg_srs.go
Labels: new feature
