Repository Consensys/gnark, pull requests merged in 2022-01, with the labels that each got.

#228 refactor: Witness API with MarshalBinary and MarshalJSON
  backend/groth16/bellman_test.go
  backend/groth16/groth16.go
  backend/plonk/plonk.go
  backend/witness/vector.go
  backend/witness/witness.go
  backend/witness/witness_test.go
  debug_test.go
  examples/plonk/main.go
  frontend/ccs.go
  frontend/schema/schema.go
  frontend/schema/schema_test.go
  frontend/schema/tags.go
  frontend/witness.go
  go.mod
  go.sum
  integration_test.go
  internal/backend/bls12-377/groth16/groth16_test.go
  internal/backend/bls12-377/plonk/plonk_test.go
  internal/backend/bls12-377/witness/witness.go
  internal/backend/bls12-381/groth16/groth16_test.go
  internal/backend/bls12-381/plonk/plonk_test.go
  internal/backend/bls12-381/witness/witness.go
  internal/backend/bls24-315/groth16/groth16_test.go
  internal/backend/bls24-315/plonk/plonk_test.go
  internal/backend/bls24-315/witness/witness.go
  internal/backend/bn254/groth16/groth16_test.go
  internal/backend/bn254/plonk/plonk_test.go
  internal/backend/bn254/witness/witness.go
  internal/backend/bw6-633/groth16/groth16_test.go
  internal/backend/bw6-633/plonk/plonk_test.go
  internal/backend/bw6-633/witness/witness.go
  internal/backend/bw6-761/groth16/groth16_test.go
  internal/backend/bw6-761/plonk/plonk_test.go
  internal/backend/bw6-761/witness/witness.go
  internal/backend/circuits/circuits.go
  internal/generator/backend/template/representations/witness.go.tmpl
  internal/generator/backend/template/zkpschemes/groth16/tests/groth16.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/tests/plonk.go.tmpl
  std/groth16_bls12377/verifier_test.go
  std/groth16_bls24315/verifier_test.go
  test/assert.go
Labels: new feature, cleanup, consolidate

#232 Group functional options in frontend, backend and test
  backend/backend.go
  backend/groth16/groth16.go
  backend/plonk/plonk.go
  examples/rollup/circuit_test.go
  frontend/ccs.go
  frontend/compile.go
  frontend/witness.go
  internal/backend/bls12-377/cs/r1cs.go
  internal/backend/bls12-377/cs/r1cs_sparse.go
  internal/backend/bls12-377/groth16/groth16_test.go
  internal/backend/bls12-377/groth16/prove.go
  internal/backend/bls12-377/plonk/plonk_test.go
  internal/backend/bls12-377/plonk/prove.go
  internal/backend/bls12-381/cs/r1cs.go
  internal/backend/bls12-381/cs/r1cs_sparse.go
  internal/backend/bls12-381/groth16/groth16_test.go
  internal/backend/bls12-381/groth16/prove.go
  internal/backend/bls12-381/plonk/plonk_test.go
  internal/backend/bls12-381/plonk/prove.go
  internal/backend/bls24-315/cs/r1cs.go
  internal/backend/bls24-315/cs/r1cs_sparse.go
  internal/backend/bls24-315/groth16/groth16_test.go
  internal/backend/bls24-315/groth16/prove.go
  internal/backend/bls24-315/plonk/plonk_test.go
  internal/backend/bls24-315/plonk/prove.go
  internal/backend/bn254/cs/r1cs.go
  internal/backend/bn254/cs/r1cs_sparse.go
  internal/backend/bn254/groth16/groth16_test.go
  internal/backend/bn254/groth16/prove.go
  internal/backend/bn254/plonk/plonk_test.go
  internal/backend/bn254/plonk/prove.go
  internal/backend/bw6-633/cs/r1cs.go
  internal/backend/bw6-633/cs/r1cs_sparse.go
  internal/backend/bw6-633/groth16/groth16_test.go
  internal/backend/bw6-633/groth16/prove.go
  internal/backend/bw6-633/plonk/plonk_test.go
  internal/backend/bw6-633/plonk/prove.go
  internal/backend/bw6-761/cs/r1cs.go
  internal/backend/bw6-761/cs/r1cs_sparse.go
  internal/backend/bw6-761/groth16/groth16_test.go
  internal/backend/bw6-761/groth16/prove.go
  internal/backend/bw6-761/plonk/plonk_test.go
  internal/backend/bw6-761/plonk/prove.go
  internal/generator/backend/template/representations/r1cs.go.tmpl
  internal/generator/backend/template/representations/r1cs.sparse.go.tmpl
  internal/generator/backend/template/zkpschemes/groth16/groth16.prove.go.tmpl
  internal/generator/backend/template/zkpschemes/groth16/tests/groth16.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/plonk.prove.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/tests/plonk.go.tmpl
  std/groth16_bls12377/verifier_test.go
  std/groth16_bls24315/verifier_test.go
  test/assert.go
  test/engine.go
  test/options.go
Labels: cleanup

#235 feat: added witness.Public to return Public part of the witness vector
  backend/witness/vector.go
  backend/witness/witness.go
  backend/witness/witness_test.go
  go.sum
Labels: new feature

#237 feat: added ccs.GetConstraints
  frontend/ccs.go
  internal/backend/bls12-377/cs/r1cs.go
  internal/backend/bls12-377/cs/r1cs_sparse.go
  internal/backend/bls12-381/cs/r1cs.go
  internal/backend/bls12-381/cs/r1cs_sparse.go
  internal/backend/bls24-315/cs/r1cs.go
  internal/backend/bls24-315/cs/r1cs_sparse.go
  internal/backend/bn254/cs/r1cs.go
  internal/backend/bn254/cs/r1cs_sparse.go
  internal/backend/bw6-633/cs/r1cs.go
  internal/backend/bw6-633/cs/r1cs_sparse.go
  internal/backend/bw6-761/cs/r1cs.go
  internal/backend/bw6-761/cs/r1cs_sparse.go
  internal/backend/compiled/cs.go
  internal/generator/backend/template/representations/r1cs.go.tmpl
  internal/generator/backend/template/representations/r1cs.sparse.go.tmpl
Labels: new feature
