Repository Consensys/gnark, pull requests merged in 2022-03, with the labels that each got.

#272 feat: added std.GetHints for convenience. fixes #264
  backend/backend.go
  backend/groth16/groth16.go
  backend/hint/builtin.go
  backend/hint/hint.go
  frontend/compiled/cs.go
  frontend/cs/r1cs/builder.go
  frontend/cs/scs/builder.go
  internal/backend/bls12-377/cs/r1cs.go
  internal/backend/bls12-377/cs/r1cs_sparse.go
  internal/backend/bls12-377/cs/solution.go
  internal/backend/bls12-381/cs/r1cs.go
  internal/backend/bls12-381/cs/r1cs_sparse.go
  internal/backend/bls12-381/cs/solution.go
  internal/backend/bls24-315/cs/r1cs.go
  internal/backend/bls24-315/cs/r1cs_sparse.go
  internal/backend/bls24-315/cs/solution.go
  internal/backend/bn254/cs/r1cs.go
  internal/backend/bn254/cs/r1cs_sparse.go
  internal/backend/bn254/cs/solution.go
  internal/backend/bw6-633/cs/r1cs.go
  internal/backend/bw6-633/cs/r1cs_sparse.go
  internal/backend/bw6-633/cs/solution.go
  internal/backend/bw6-761/cs/r1cs.go
  internal/backend/bw6-761/cs/r1cs_sparse.go
  internal/backend/bw6-761/cs/solution.go
  internal/generator/backend/template/representations/r1cs.go.tmpl
  internal/generator/backend/template/representations/r1cs.sparse.go.tmpl
  internal/generator/backend/template/representations/solution.go.tmpl
  std/algebra/sw_bls12377/g1.go
  std/algebra/sw_bls24315/g1.go
  std/hints.go
Labels: consolidate

#276 Adds std/math/bits
  backend/hint/builtin.go
  examples/exponentiate/exponentiate.go
  frontend/cs/r1cs/api.go
  frontend/cs/r1cs/api_assertions.go
  frontend/cs/scs/api.go
  frontend/cs/scs/api_assertions.go
  std/hints.go
  std/math/bits/conversion.go
  std/math/bits/conversion_binary.go
  std/math/bits/conversion_ternary.go
  std/math/bits/conversion_test.go
  std/math/bits/naf.go
  std/math/bits/naf_test.go
  test/assert.go
  test/engine_test.go
Labels: new feature

#279 Adds internal/stats package
  circuitstats_test.go
  init.stats
  internal/stats/generate/main.go
  internal/stats/latest.stats
  internal/stats/snippet.go
  internal/stats/stats.go
  internal/stats/stats_test.go
  internal/utils/circuit.go
Labels: new feature, consolidate

#280 simplify post compile phase: shifting wire id is not needed 🙈
  frontend/compile.go
  frontend/cs/r1cs/builder.go
  frontend/cs/scs/builder.go
Labels: cleanup, consolidate

#285 refactor: eddsa factorizing and code cleaning
  examples/rollup/circuit.go
  examples/rollup/rollup_test.go
  frontend/compile.go
  go.mod
  go.sum
  internal/stats/latest.stats
  std/algebra/twistededwards/bandersnatch/.point.go.swp
  std/algebra/twistededwards/bandersnatch/curve.go
  std/algebra/twistededwards/bandersnatch/point_test.go
  std/algebra/twistededwards/curve.go
  std/algebra/twistededwards/curve_test.go
  std/algebra/twistededwards/point.go
  std/algebra/twistededwards/point_test.go
  std/algebra/twistededwards/scalarmul_glv.go
  std/algebra/twistededwards/twistededwards.go
  std/hints.go
  std/signature/eddsa/eddsa.go
  std/signature/eddsa/eddsa_test.go
  test/assert.go
  test/kzg_srs.go
Labels: consolidate

#286 clean: remove PairingContext and Extension objects from api calls in std/.../pairing
  internal/stats/snippet.go
  std/algebra/fields_bls12377/e12.go
  std/algebra/fields_bls12377/e12_test.go
  std/algebra/fields_bls12377/e2.go
  std/algebra/fields_bls12377/e2_test.go
  std/algebra/fields_bls12377/e6.go
  std/algebra/fields_bls12377/e6_test.go
  std/algebra/fields_bls24315/e12.go
  std/algebra/fields_bls24315/e12_test.go
  std/algebra/fields_bls24315/e2.go
  std/algebra/fields_bls24315/e24.go
  std/algebra/fields_bls24315/e24_test.go
  std/algebra/fields_bls24315/e2_test.go
  std/algebra/fields_bls24315/e4.go
  std/algebra/fields_bls24315/e4_test.go
  std/algebra/sw_bls12377/g2.go
  std/algebra/sw_bls12377/g2_test.go
  std/algebra/sw_bls12377/pairing.go
  std/algebra/sw_bls12377/pairing_test.go
  std/algebra/sw_bls24315/g2.go
  std/algebra/sw_bls24315/g2_test.go
  std/algebra/sw_bls24315/pairing.go
  std/algebra/sw_bls24315/pairing_test.go
  std/groth16_bls12377/verifier.go
  std/groth16_bls12377/verifier_test.go
  std/groth16_bls24315/verifier.go
  std/groth16_bls24315/verifier_test.go
Labels: cleanup

#263 ScalarMul on Bandersnatch
  examples/rollup/circuit.go
  examples/rollup/rollup_test.go
  frontend/compile.go
  go.mod
  go.sum
  internal/stats/latest.stats
  std/algebra/twistededwards/bandersnatch/curve.go
  std/algebra/twistededwards/bandersnatch/point.go
  std/algebra/twistededwards/bandersnatch/point_test.go
  std/algebra/twistededwards/curve.go
  std/algebra/twistededwards/curve_test.go
  std/algebra/twistededwards/point.go
  std/algebra/twistededwards/point_test.go
  std/algebra/twistededwards/scalarmul_glv.go
  std/algebra/twistededwards/twistededwards.go
  std/signature/eddsa/eddsa.go
  std/signature/eddsa/eddsa_test.go
  test/assert.go
Labels: perf

#295 fix: add whitespace between vars in test.Println
  test/engine.go
Labels: bug

#298 fix: err instead of panic when recursively solving hints
  internal/backend/bls12-377/cs/solution.go
  internal/backend/bls12-381/cs/solution.go
  internal/backend/bls24-315/cs/solution.go
  internal/backend/bn254/cs/solution.go
  internal/backend/bw6-633/cs/solution.go
  internal/backend/bw6-761/cs/solution.go
  internal/generator/backend/template/representations/solution.go.tmpl
Labels: bug
