Repository Consensys/gnark, pull requests merged in 2023-02, with the labels that each got.

#452 feat: add cs.GetConstraint with examples, and pretty printer helpers
  constraint/bls12-377/coeff.go
  constraint/bls12-377/r1cs.go
  constraint/bls12-377/r1cs_sparse.go
  constraint/bls12-381/coeff.go
  constraint/bls12-381/r1cs.go
  constraint/bls12-381/r1cs_sparse.go
  constraint/bls24-315/coeff.go
  constraint/bls24-315/r1cs.go
  constraint/bls24-315/r1cs_sparse.go
  constraint/bls24-317/coeff.go
  constraint/bls24-317/r1cs.go
  constraint/bls24-317/r1cs_sparse.go
  constraint/bn254/coeff.go
  constraint/bn254/r1cs.go
  constraint/bn254/r1cs_sparse.go
  constraint/bw6-633/coeff.go
  constraint/bw6-633/r1cs.go
  constraint/bw6-633/r1cs_sparse.go
  constraint/bw6-761/coeff.go
  constraint/bw6-761/r1cs.go
  constraint/bw6-761/r1cs_sparse.go
  constraint/coeff.go
  constraint/linear_expression.go
  constraint/r1cs.go
  constraint/r1cs_sparse.go
  constraint/r1cs_sparse_test.go
  constraint/r1cs_test.go
  constraint/string_utils.go
  constraint/system.go
  constraint/term.go
  constraint/tinyfield/coeff.go
  constraint/tinyfield/r1cs.go
  constraint/tinyfield/r1cs_sparse.go
  frontend/cs/r1cs/builder.go
  internal/generator/backend/template/representations/coeff.go.tmpl
  internal/generator/backend/template/representations/r1cs.go.tmpl
  internal/generator/backend/template/representations/r1cs.sparse.go.tmpl
Labels: cleanup, consolidate

#296 feat: add NoFuzzing() testing option
  test/assert.go
  test/options.go
Labels: new feature

#459 fix: mark output of AND in R1CS as boolean
  frontend/cs/r1cs/api.go
Labels: bug

#482 fix: allocate new variable in engine.MulAcc
  std/math/emulated/field_ops.go
  test/engine.go
Labels: bug

#480 feat: add simple key-value store to the builders
  frontend/cs/r1cs/builder.go
  frontend/cs/scs/builder.go
  internal/kvstore/kvstore.go
  test/engine.go
  test/solver_test.go
Labels: new feature

#481 refactor: define Committer interface for builders
  frontend/builder.go
  frontend/cs/r1cs/builder.go
  frontend/cs/scs/builder.go
  go.mod
  internal/backend/bls12-377/groth16/commitment_test.go
  internal/backend/bls12-381/groth16/commitment_test.go
  internal/backend/bls24-315/groth16/commitment_test.go
  internal/backend/bls24-317/groth16/commitment_test.go
  internal/backend/bn254/groth16/commitment_test.go
  internal/backend/bw6-633/groth16/commitment_test.go
  internal/backend/bw6-761/groth16/commitment_test.go
  internal/generator/backend/template/zkpschemes/groth16/tests/groth16.commitment.go.tmpl
  test/engine.go
Labels: consolidate

#483 feat: add defer to the Compiler interface
  debug/debug.go
  debug/symbol_table.go
  frontend/builder.go
  frontend/compile.go
  frontend/cs/r1cs/builder.go
  frontend/cs/r1cs/r1cs_test.go
  frontend/cs/scs/builder.go
  internal/circuitdefer/defer.go
  test/engine.go
  test/engine_test.go
  test/solver_test.go
Labels: new feature, proposition
