Repository Consensys/gnark, pull requests merged in 2023-12, with the labels that each got.

#749 perf: non-native modular multiplication
  internal/stats/latest.stats
  std/math/emulated/doc.go
  std/math/emulated/element.go
  std/math/emulated/field.go
  std/math/emulated/field_assert.go
  std/math/emulated/field_mul.go
  std/math/emulated/field_ops.go
  std/math/emulated/hints.go
  std/multicommit/nativecommit.go
Labels: perf, zk-evm, P1: High

#949 Perf: plonk verifier gadget
  internal/generator/backend/template/zkpschemes/plonk/plonk.marshal.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/tests/marshal.go.tmpl
  internal/stats/latest.stats
  internal/stats/snippet.go
  std/algebra/emulated/fields_bw6761/e3.go
  std/algebra/emulated/fields_bw6761/e6.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/sw_bls12381/g2.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/pairing_test.go
  std/algebra/emulated/sw_bls12381/precomputations.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
  std/algebra/emulated/sw_bn254/precomputations.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/precomputations.go
  std/algebra/emulated/sw_emulated/hints.go
  std/algebra/emulated/sw_emulated/params.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/interfaces.go
  std/algebra/native/fields_bls12377/e12_pairing.go
  std/algebra/native/fields_bls12377/e12_test.go
  std/algebra/native/fields_bls24315/e24_pairing.go
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls12377/g1_test.go
  std/algebra/native/sw_bls12377/g2.go
  std/algebra/native/sw_bls12377/g2_test.go
  std/algebra/native/sw_bls12377/inner.go
  std/algebra/native/sw_bls12377/pairing.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls12377/pairing_test.go
  std/algebra/native/sw_bls12377/precomputations.go
  std/algebra/native/sw_bls24315/g1.go
  std/algebra/native/sw_bls24315/g1_test.go
  std/algebra/native/sw_bls24315/g2.go
  std/algebra/native/sw_bls24315/g2_test.go
  std/algebra/native/sw_bls24315/inner.go
  std/algebra/native/sw_bls24315/pairing.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/algebra/native/sw_bls24315/pairing_test.go
  std/algebra/native/sw_bls24315/precomputations.go
  std/commitments/kzg/verifier.go
  std/commitments/kzg/verifier_test.go
  std/evmprecompiles/07-bnmul.go
  std/hints.go
  std/recursion/plonk/verifier.go
  std/recursion/plonk/verifier_test.go
Labels: perf

#874 Perf: KZG verify gadget
  internal/generator/backend/template/zkpschemes/plonk/plonk.marshal.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/tests/marshal.go.tmpl
  internal/stats/latest.stats
  internal/stats/snippet.go
  std/algebra/emulated/sw_bls12381/g2.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/pairing_test.go
  std/algebra/emulated/sw_bls12381/precomputations.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
  std/algebra/emulated/sw_bn254/precomputations.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/precomputations.go
  std/algebra/native/sw_bls12377/g2.go
  std/algebra/native/sw_bls12377/g2_test.go
  std/algebra/native/sw_bls12377/inner.go
  std/algebra/native/sw_bls12377/pairing.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls12377/pairing_test.go
  std/algebra/native/sw_bls12377/precomputations.go
  std/algebra/native/sw_bls24315/g2.go
  std/algebra/native/sw_bls24315/g2_test.go
  std/algebra/native/sw_bls24315/inner.go
  std/algebra/native/sw_bls24315/pairing.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/algebra/native/sw_bls24315/pairing_test.go
  std/algebra/native/sw_bls24315/precomputations.go
  std/commitments/kzg/verifier.go
  std/commitments/kzg/verifier_test.go
  std/recursion/plonk/verifier.go
  std/recursion/plonk/verifier_test.go
Labels: perf, zk-evm, P1: High

#975 perf(ecdsa): use GLV in JointScalarMulBase
  std/algebra/emulated/sw_emulated/point.go
Labels: perf, zk-evm, P1: High

#974 chore: adapt changes from native Fiat-Shamir transcript
  backend/plonk/bls12-377/prove.go
  backend/plonk/bls12-377/verify.go
  backend/plonk/bls12-381/prove.go
  backend/plonk/bls12-381/verify.go
  backend/plonk/bls24-315/prove.go
  backend/plonk/bls24-315/verify.go
  backend/plonk/bls24-317/prove.go
  backend/plonk/bls24-317/verify.go
  backend/plonk/bn254/prove.go
  backend/plonk/bn254/verify.go
  backend/plonk/bw6-633/prove.go
  backend/plonk/bw6-633/verify.go
  backend/plonk/bw6-761/prove.go
  backend/plonk/bw6-761/verify.go
  backend/plonkfri/bls12-377/prove.go
  backend/plonkfri/bls12-377/verify.go
  backend/plonkfri/bls12-381/prove.go
  backend/plonkfri/bls12-381/verify.go
  backend/plonkfri/bls24-315/prove.go
  backend/plonkfri/bls24-315/verify.go
  backend/plonkfri/bls24-317/prove.go
  backend/plonkfri/bls24-317/verify.go
  backend/plonkfri/bn254/prove.go
  backend/plonkfri/bn254/verify.go
  backend/plonkfri/bw6-633/prove.go
  backend/plonkfri/bw6-633/verify.go
  backend/plonkfri/bw6-761/prove.go
  backend/plonkfri/bw6-761/verify.go
  constant/constant.go
  go.mod
  go.sum
  internal/generator/backend/main.go
  internal/generator/backend/template/representations/constant.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/plonk.prove.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/plonk.verify.go.tmpl
  internal/generator/backend/template/zkpschemes/plonkfri/plonk.prove.go.tmpl
  internal/generator/backend/template/zkpschemes/plonkfri/plonk.verify.go.tmpl
  std/commitments/fri/fri.go
  std/commitments/fri/utils.go
  std/fiat-shamir/transcript.go
  std/fiat-shamir/transcript_test.go
  std/recursion/wrapped_hash.go
  std/sumcheck/sumcheck.go
Labels: consolidate, zk-evm, P1: High
