Repository Consensys/gnark, pull requests merged in 2023-05, with the labels that each got.

#673 Adds ground work for custom blueprints. Fixes #660
  constraint/bls12-377/coeff.go
  constraint/bls12-377/solver.go
  constraint/bls12-377/system.go
  constraint/bls12-381/coeff.go
  constraint/bls12-381/solver.go
  constraint/bls12-381/system.go
  constraint/bls24-315/coeff.go
  constraint/bls24-315/solver.go
  constraint/bls24-315/system.go
  constraint/bls24-317/coeff.go
  constraint/bls24-317/solver.go
  constraint/bls24-317/system.go
  constraint/blueprint.go
  constraint/blueprint_hint.go
  constraint/blueprint_r1cs.go
  constraint/blueprint_scs.go
  constraint/bn254/coeff.go
  constraint/bn254/solver.go
  constraint/bn254/system.go
  constraint/bw6-633/coeff.go
  constraint/bw6-633/solver.go
  constraint/bw6-633/system.go
  constraint/bw6-761/coeff.go
  constraint/bw6-761/solver.go
  constraint/bw6-761/system.go
  constraint/core.go
  constraint/field.go
  constraint/hint.go
  constraint/level_builder.go
  constraint/linear_expression.go
  constraint/r1cs.go
  constraint/r1cs_sparse.go
  constraint/system.go
  constraint/term.go
  constraint/tinyfield/coeff.go
  constraint/tinyfield/solver.go
  constraint/tinyfield/system.go
  frontend/builder.go
  frontend/cs/r1cs/builder.go
  frontend/cs/scs/builder.go
  frontend/internal/expr/linear_expression.go
  frontend/internal/expr/term.go
  internal/generator/backend/template/representations/coeff.go.tmpl
  internal/generator/backend/template/representations/solver.go.tmpl
  internal/generator/backend/template/representations/system.go.tmpl
  std/hints.go
  std/lookup/logderivlookup/blueprint.go
  std/lookup/logderivlookup/logderivlookup.go
  std/lookup/logderivlookup/logderivlookup_test.go
  test/blueprint_solver.go
  test/blueprint_solver_test.go
  test/engine.go
Labels: zk-evm

#664 Refactor, perf: 2-chains pairing + groth16 API
  internal/stats/latest.stats
  internal/stats/snippet.go
  std/algebra/native/fields_bls12377/e12.go
  std/algebra/native/fields_bls12377/e12_pairing.go
  std/algebra/native/fields_bls12377/e6.go
  std/algebra/native/fields_bls24315/e24_pairing.go
  std/algebra/native/sw_bls12377/pairing.go
  std/algebra/native/sw_bls24315/pairing.go
  std/groth16_bls12377/verifier.go
  std/groth16_bls12377/verifier_test.go
  std/groth16_bls24315/verifier.go
  std/groth16_bls24315/verifier_test.go
Labels: consolidate, perf

#695 fix: init elements in arrays and slices if have init hook
  backend/witness/witness_test.go
  frontend/schema/schema.go
  frontend/schema/schema_test.go
  frontend/schema/walk.go
Labels: bug

#656 feat: differentiate ecrecover with strict and lax check for s
  std/evmprecompiles/01-ecrecover.go
  std/evmprecompiles/01-ecrecover_test.go
Labels: consolidate, zk-evm, P1: High

#696 refactor: emulation parameters
  std/math/emulated/emparams/emparams.go
  std/math/emulated/params.go
Labels: new feature, cleanup, consolidate, P3: Low

#697 feat: implement NIST P-256 and P-384 curves
  std/algebra/emulated/sw_emulated/params.go
  std/algebra/emulated/sw_emulated/params_compute.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/signature/ecdsa/ecdsa_secpr_test.go
Labels: new feature, P3: Low

#706 perf(2-chain/varScalarMul): use DoubleAndAdd to reduce #constraints
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls12377/g2.go
Labels: perf
