Repository Consensys/gnark, pull requests merged in 2023-06, with the labels that each got.

#689 feat: add sha2 primitive
  internal/backend/circuits/hint.go
  std/accumulator/merkle/verify.go
  std/commitments/fri/fri.go
  std/fiat-shamir/settings.go
  std/fiat-shamir/transcript.go
  std/gkr/gkr_test.go
  std/hash/hash.go
  std/hash/sha2/sha2.go
  std/hash/sha2/sha2_test.go
  std/hints.go
  std/internal/logderivprecomp/logderivprecomp.go
  std/internal/logderivprecomp/logderivprecomp_test.go
  std/math/bits/conversion_binary.go
  std/math/bits/conversion_ternary.go
  std/math/bits/hints.go
  std/math/bits/naf.go
  std/math/bitslice/hints.go
  std/math/bitslice/opts.go
  std/math/bitslice/partition.go
  std/math/bitslice/partition_test.go
  std/math/uints/hints.go
  std/math/uints/uint8.go
  std/math/uints/uint8_test.go
  std/permutation/keccakf/keccak_test.go
  std/permutation/keccakf/keccakf.go
  std/permutation/keccakf/uint64api.go
  std/permutation/keccakf/uint64api_test.go
  std/permutation/sha2/sha2block.go
  std/permutation/sha2/sha2block_test.go
  std/signature/eddsa/eddsa.go
  test/engine_test.go
Labels: new feature, zk-evm, P1: High

#723 serialization: include round-trip tests in CI
  backend/groth16/bls12-377/marshal.go
  backend/groth16/bls12-377/marshal_test.go
  backend/groth16/bls12-381/marshal.go
  backend/groth16/bls12-381/marshal_test.go
  backend/groth16/bls24-315/marshal.go
  backend/groth16/bls24-315/marshal_test.go
  backend/groth16/bls24-317/marshal.go
  backend/groth16/bls24-317/marshal_test.go
  backend/groth16/bn254/marshal.go
  backend/groth16/bn254/marshal_test.go
  backend/groth16/bw6-633/marshal.go
  backend/groth16/bw6-633/marshal_test.go
  backend/groth16/bw6-761/marshal.go
  backend/groth16/bw6-761/marshal_test.go
  backend/plonk/bls12-377/marshal.go
  backend/plonk/bls12-377/marshal_test.go
  backend/plonk/bls12-381/marshal.go
  backend/plonk/bls12-381/marshal_test.go
  backend/plonk/bls24-315/marshal.go
  backend/plonk/bls24-315/marshal_test.go
  backend/plonk/bls24-317/marshal.go
  backend/plonk/bls24-317/marshal_test.go
  backend/plonk/bn254/marshal.go
  backend/plonk/bn254/marshal_test.go
  backend/plonk/bw6-633/marshal.go
  backend/plonk/bw6-633/marshal_test.go
  backend/plonk/bw6-761/marshal.go
  backend/plonk/bw6-761/marshal_test.go
  go.mod
  go.sum
  internal/generator/backend/template/zkpschemes/groth16/groth16.marshal.go.tmpl
  internal/generator/backend/template/zkpschemes/groth16/tests/groth16.marshal.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/plonk.marshal.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/tests/marshal.go.tmpl
  test/assert.go
Labels: bug

#731 fix: emulated ToBits
  std/math/emulated/element_test.go
  std/math/emulated/field_binary.go
Labels: bug, zk-evm
