Repository Consensys/gnark, pull requests merged in 2023-10, with the labels that each got.

#857 fix typos
  backend/groth16/bn254/solidity.go
  backend/plonk/bls12-377/setup.go
  backend/plonk/bls12-381/setup.go
  backend/plonk/bls24-315/setup.go
  backend/plonk/bls24-317/setup.go
  backend/plonk/bn254/setup.go
  backend/plonk/bn254/solidity.go
  backend/plonk/bw6-633/setup.go
  backend/plonk/bw6-761/setup.go
  backend/plonkfri/bls12-377/setup.go
  backend/plonkfri/bls12-381/setup.go
  backend/plonkfri/bls24-315/setup.go
  backend/plonkfri/bls24-317/setup.go
  backend/plonkfri/bn254/setup.go
  backend/plonkfri/bw6-633/setup.go
  backend/plonkfri/bw6-761/setup.go
  constraint/core.go
  examples/rollup/error.go
  internal/generator/backend/template/zkpschemes/plonk/plonk.setup.go.tmpl
  internal/generator/backend/template/zkpschemes/plonkfri/plonk.setup.go.tmpl
Labels: doc

#846 feat: BW6-761 emulated pairing
  go.mod
  go.sum
  std/algebra/emulated/fields_bw6761/doc.go
  std/algebra/emulated/fields_bw6761/e3.go
  std/algebra/emulated/fields_bw6761/e3_test.go
  std/algebra/emulated/fields_bw6761/e6.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/fields_bw6761/e6_test.go
  std/algebra/emulated/fields_bw6761/hints.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bw6761/doc.go
  std/algebra/emulated/sw_bw6761/doc_test.go
  std/algebra/emulated/sw_bw6761/g1.go
  std/algebra/emulated/sw_bw6761/g2.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/pairing_test.go
  std/math/emulated/emparams/emparams.go
  std/math/emulated/params.go
Labels: new feature, zk-evm

#866 Feat: BW6-761 KZG gadget
  std/algebra/defaults.go
  std/algebra/emulated/sw_bw6761/g1.go
  std/algebra/emulated/sw_emulated/params.go
  std/algebra/emulated/sw_emulated/params_compute.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/commitments/kzg/verifier.go
  std/commitments/kzg/verifier_test.go
Labels: consolidate

#861 chore: avoid nonnative dereferences
  std/algebra/emulated/fields_bls12381/e12_pairing.go
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bn254/pairing.go
Labels: consolidate

#878 chore: cleanup documentation examples
  std/algebra/emulated/sw_bls12381/doc_test.go
  std/algebra/emulated/sw_bn254/doc_test.go
  std/algebra/emulated/sw_bw6761/doc_test.go
  std/commitments/kzg/native_doc_test.go
  std/commitments/kzg/nonnative_doc_test.go
  std/lookup/logderivlookup/doc_test.go
  std/math/cmp/doc_isless_test.go
  std/math/emulated/doc_example_field_test.go
  std/math/emulated/field_hint_test.go
  std/multicommit/doc_test.go
  std/recursion/groth16/native_doc_test.go
  std/recursion/groth16/nonnative_doc_test.go
  std/selector/doc_map_test.go
  std/selector/doc_mux_test.go
  std/selector/doc_partition_test.go
Labels: consolidate, P3: Low, doc

#876 Refactor(BW6-761): use revisited Ate pairing instead of Tate
  go.mod
  go.sum
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/fields_bw6761/e6_test.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/pairing_test.go
  std/algebra/emulated/sw_bw6761/precomputations.go
Labels: new feature, perf

#884 feat: add short-hash wrappers for recursion
  std/recursion/wrapped_hash.go
  std/recursion/wrapped_hash_test.go
Labels: new feature, consolidate, zk-evm, P1: High
