Repository Consensys/gnark, pull requests merged in 2023-04, with the labels that each got.

#613 Fix(emulated pairing): edge cases in torus-based final exp
  std/algebra/emulated/fields_bls12381/e12.go
  std/algebra/emulated/fields_bls12381/e12_test.go
  std/algebra/emulated/fields_bls12381/e2.go
  std/algebra/emulated/fields_bls12381/e2_test.go
  std/algebra/emulated/fields_bls12381/e6.go
  std/algebra/emulated/fields_bls12381/e6_test.go
  std/algebra/emulated/fields_bn254/e12.go
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/fields_bn254/e12_test.go
  std/algebra/emulated/fields_bn254/e2.go
  std/algebra/emulated/fields_bn254/e2_test.go
  std/algebra/emulated/fields_bn254/e6.go
  std/algebra/emulated/fields_bn254/e6_test.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/pairing_test.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
Labels: zk-evm

#488 feat: add EVM precompiles
  std/evmprecompiles/01-ecrecover.go
  std/evmprecompiles/01-ecrecover_test.go
  std/evmprecompiles/02-sha256.go
  std/evmprecompiles/04-id.go
  std/evmprecompiles/05-expmod.go
  std/evmprecompiles/06-bnadd.go
  std/evmprecompiles/07-bnmul.go
  std/evmprecompiles/08-bnpairing.go
  std/evmprecompiles/bn_test.go
  std/evmprecompiles/compose.go
  std/evmprecompiles/doc.go
  std/evmprecompiles/hints.go
  std/hints.go
  std/math/emulated/field.go
Labels: new feature, zk-evm

#625 perf: use `api.Select` for 2 to 1 mux
  std/selector/multiplexer.go
  std/selector/multiplexer_test.go
Labels: perf

#623 feat: add modular square root in field emulation
  std/math/emulated/element_test.go
  std/math/emulated/field_ops.go
  std/math/emulated/hints.go
Labels: new feature

#603 fix: field emulation subtract padding compute
  internal/stats/latest.stats
  std/math/emulated/field_ops.go
Labels: bug

#631 Feat: unified ECADD
  std/algebra/emulated/sw_emulated/doc.go
  std/algebra/emulated/sw_emulated/doc_test.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/evmprecompiles/01-ecrecover.go
  std/evmprecompiles/06-bnadd.go
  std/signature/ecdsa/ecdsa.go
Labels: bug, zk-evm

#620 feat: log-derivative vector lookups
  internal/stats/latest.stats
  std/hints.go
  std/internal/logderivarg/logderivarg.go
  std/lookup/logderivlookup/doc_test.go
  std/lookup/logderivlookup/logderivlookup.go
  std/lookup/logderivlookup/logderivlookup_test.go
  std/rangecheck/rangecheck.go
  std/rangecheck/rangecheck_commit.go
Labels: new feature, zk-evm

#651 [BUG FIX] constraint: serializeCommitment
  constraint/commitment.go
Labels: bug

#658 Perf: KZG verification circuit in a single point
  std/commitments/kzg_bls12377/verifier.go
  std/commitments/kzg_bls24315/verifier.go
Labels: perf

#661 perf(ecdsa): JoinScalarMulBase avoids 0 edge-cases
  std/algebra/emulated/sw_emulated/point.go
  std/evmprecompiles/01-ecrecover.go
  std/signature/ecdsa/ecdsa.go
Labels: perf, zk-evm
