Repository Consensys/gnark, pull requests merged in 2023-03, with the labels that each got.

#503 docs: fix select description in field emulation
  std/math/emulated/field_ops.go
Labels: bug

#497 perf: in-circuit ECDSA on secp256k1
  std/algebra/weierstrass/doc.go
  std/algebra/weierstrass/params.go
  std/algebra/weierstrass/params_compute.go
  std/algebra/weierstrass/point.go
  std/algebra/weierstrass/point_test.go
  std/signature/ecdsa/ecdsa.go
  std/signature/ecdsa/ecdsa_test.go
Labels: perf

#506 Perf: KZG in circuit
  std/algebra/fields_bls12377/e2.go
  std/algebra/fields_bls24315/e2.go
  std/algebra/fields_bls24315/e4.go
  std/algebra/sw_bls12377/g1.go
  std/algebra/sw_bls12377/g1_test.go
  std/algebra/sw_bls12377/g2.go
  std/algebra/sw_bls12377/g2_test.go
  std/algebra/sw_bls12377/inner.go
  std/algebra/sw_bls12377/inner_compute.go
  std/algebra/sw_bls24315/g1.go
  std/algebra/sw_bls24315/g1_test.go
  std/algebra/sw_bls24315/g2.go
  std/algebra/sw_bls24315/g2_test.go
  std/algebra/sw_bls24315/inner.go
  std/algebra/sw_bls24315/inner_compute.go
  std/commitments/kzg_bls12377/verifier.go
  std/commitments/kzg_bls12377/verifier_test.go
  std/commitments/kzg_bls24315/verifier.go
  std/commitments/kzg_bls24315/verifier_test.go
Labels: perf

#518 fix: restrict constants in field emulation to width
  std/math/emulated/field.go
Labels: bug

#519 chore: remove heavy profiling and compiling
  std/signature/ecdsa/ecdsa_test.go
Labels: cleanup

#521 fix: handle stack traces with deferred function
  backend/witness/witness_test.go
  debug/debug.go
  debug/symbol_table.go
  frontend/compile.go
  test/engine.go
  test/solver_test.go
Labels: bug

#534 fix: initialize new variable if field emulation multiplication check
  frontend/api.go
  std/math/emulated/field_ops.go
Labels: bug, consolidate

#533 fix: stable levelbuilder hint mapping
  constraint/level_builder.go
  constraint/level_builder_test.go
Labels: bug

#507 fix: allow unreplaced BSB22 commitment hint in solver
  frontend/cs/r1cs/api.go
Labels: bug

#538 feat: gnark/profile now filter frontend private method fixes #537
  go.sum
  profile/profile.go
  profile/profile_test.go
  profile/profile_worker.go
Labels: bug, consolidate

#472 feat: range check gadget
  frontend/builder.go
  frontend/cs/r1cs/builder.go
  frontend/cs/scs/api.go
  internal/frontendtype/frontendtype.go
  internal/stats/latest.stats
  std/hints.go
  std/math/emulated/field.go
  std/math/emulated/field_assert.go
  std/math/emulated/hints.go
  std/rangecheck/rangecheck.go
  std/rangecheck/rangecheck_commit.go
  std/rangecheck/rangecheck_plain.go
  std/rangecheck/rangecheck_test.go
Labels: new feature

#550 fix: do not pass limb width enforcement for consts in AssertIsEqual
  std/math/emulated/field_assert.go
  test/assert.go
Labels: bug

#560 fix: use mocked api.Commit also in Windows tests
  frontend/cs/r1cs/api.go
Labels: bug

#547 feat: reintroduce hints for field emulation
  std/math/emulated/field_hint.go
  std/math/emulated/field_hint_test.go
  test/options.go
Labels: new feature

#579 fix: subtraction overflow computation bug
  internal/stats/latest.stats
  std/math/emulated/field.go
  std/math/emulated/field_assert.go
  std/math/emulated/field_ops.go
Labels: bug

#566 Perf: emulated BN254 pairing
  go.mod
  go.sum
  std/algebra/emulated/fields_bn254/e12.go
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/fields_bn254/e12_test.go
  std/algebra/emulated/fields_bn254/e2.go
  std/algebra/emulated/fields_bn254/e2_test.go
  std/algebra/emulated/fields_bn254/e6.go
  std/algebra/emulated/fields_bn254/e6_test.go
  std/algebra/emulated/fields_bn254/hints.go
  std/algebra/emulated/sw_bn254/doc.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
Labels: perf, zk-evm

#594 Perf: optimise BN254 emulated final exponentiation
  std/algebra/emulated/fields_bn254/e12.go
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/fields_bn254/e12_test.go
  std/algebra/emulated/fields_bn254/e6.go
  std/algebra/emulated/fields_bn254/e6_test.go
  std/algebra/emulated/fields_bn254/hints.go
  std/algebra/emulated/sw_bn254/pairing.go
Labels: perf, zk-evm

#591 Feat: emulated BLS12-381 pairing
  go.mod
  go.sum
  std/algebra/emulated/fields_bls12381/doc.go
  std/algebra/emulated/fields_bls12381/e12.go
  std/algebra/emulated/fields_bls12381/e12_pairing.go
  std/algebra/emulated/fields_bls12381/e12_test.go
  std/algebra/emulated/fields_bls12381/e2.go
  std/algebra/emulated/fields_bls12381/e2_test.go
  std/algebra/emulated/fields_bls12381/e6.go
  std/algebra/emulated/fields_bls12381/e6_test.go
  std/algebra/emulated/fields_bls12381/hints.go
  std/algebra/emulated/sw_bls12381/doc.go
  std/algebra/emulated/sw_bls12381/doc_test.go
  std/algebra/emulated/sw_bls12381/g1.go
  std/algebra/emulated/sw_bls12381/g2.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/pairing_test.go
  std/math/emulated/params.go
Labels: new feature

#599 feat: set default compression threshold
  frontend/compile.go
  internal/stats/latest.stats
Labels: perf

#583 feat: range checks using log derivative, fixes #581
  frontend/cs/r1cs/api.go
  internal/stats/latest.stats
  std/rangecheck/rangecheck.go
  std/rangecheck/rangecheck_commit.go
  std/rangecheck/rangecheck_test.go
Labels: perf

#562 feat: add gadget for enabling multiple commitments in-circuit
  frontend/compile.go
  internal/circuitdefer/defer.go
  std/internal/multicommit/doc_test.go
  std/internal/multicommit/nativecommit.go
  std/internal/multicommit/nativecommit_test.go
  std/rangecheck/rangecheck_commit.go
  std/rangecheck/rangecheck_test.go
  test/engine.go
Labels: new feature, zk-evm
