Repository Consensys/gnark, pull requests merged in 2023-07, with the labels that each got.

#708 Feat: fixed-argument emulated pairing
  std/algebra/emulated/sw_bls12381/g2_test.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/pairing_test.go
  std/algebra/emulated/sw_bls12381/precomputations.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
  std/algebra/emulated/sw_bn254/precomputations.go
  std/algebra/native/fields_bls24315/e24_pairing.go
  std/algebra/native/sw_bls12377/pairing.go
  std/algebra/native/sw_bls12377/pairing_test.go
  std/algebra/native/sw_bls12377/precomputations.go
  std/algebra/native/sw_bls24315/pairing.go
  std/algebra/native/sw_bls24315/pairing_test.go
  std/algebra/native/sw_bls24315/precomputations.go
Labels: new feature, perf

#726 Perf: Add-only emulated scalar multiplication
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
Labels: perf, zk-evm

#698 feat: emulated pairing 2-by-2 fixed circuit for EVM
  std/algebra/emulated/sw_bn254/pairing.go
  std/evmprecompiles/08-bnpairing.go
  std/evmprecompiles/bn_test.go
Labels: zk-evm

#714 Perf: emulated pairing BN254
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
Labels: perf

#758 feat: [PLONK_AUDIT_4-15] fixes 757
  backend/plonk/bn254/solidity.go
Labels: zk-evm

#763 fix: do not accumulate terms with zero coefficient for addition
  frontend/cs/scs/builder.go
  frontend/cs/scs/duplicate_test.go
  internal/stats/latest.stats
Labels: bug

#760 perf: ELM03+Joye07 for emulated scalarMul
  std/algebra/emulated/sw_emulated/point.go
Labels: perf, zk-evm

#775 feat: zeta_power_n_minus_one save and reused in compute_pi
  backend/plonk/bn254/solidity.go
Labels: perf, zk-evm

#783 Perf: save 1 `Select` at each iteration in the emulated `scalarMul`
  std/algebra/emulated/sw_emulated/point.go
Labels: perf, zk-evm

#795 Feat/clean compute pi
  backend/plonk/bn254/solidity.go
Labels: consolidate, zk-evm
