Repository Consensys/gnark, pull requests merged in 2023-11, with the labels that each got.

#899 perf: lookup blueprint compile time improvement
  constraint/bls12-377/r1cs_test.go
  constraint/bls12-381/r1cs_test.go
  constraint/bls24-315/r1cs_test.go
  constraint/bls24-317/r1cs_test.go
  constraint/blueprint.go
  constraint/blueprint_hint.go
  constraint/blueprint_logderivlookup.go
  constraint/blueprint_r1cs.go
  constraint/blueprint_scs.go
  constraint/bn254/r1cs_test.go
  constraint/bw6-633/r1cs_test.go
  constraint/bw6-761/r1cs_test.go
  constraint/core.go
  constraint/instruction_tree.go
  constraint/level_builder.go
  constraint/tinyfield/r1cs_test.go
  internal/generator/backend/template/representations/tests/r1cs.go.tmpl
  std/lookup/logderivlookup/logderivlookup_test.go
Labels: perf

#900 feat: Fiat-Shamir transcript using a short hash
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/native/sw_bls12377/g1_test.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls24315/g1_test.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/commitments/fri/fri.go
  std/fiat-shamir/transcript.go
  std/fiat-shamir/transcript_test.go
  std/gkr/gkr.go
  std/recursion/wrapped_hash.go
  std/recursion/wrapped_hash_test.go
  std/sumcheck/sumcheck.go
Labels: new feature, zk-evm, P1: High

#901 refactor: use emulated.FieldParams as type parameter to generic Curve and Pairing
  std/algebra/defaults.go
  std/algebra/emulated/sw_bls12381/g1.go
  std/algebra/emulated/sw_bls12381/g2.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/precomputations.go
  std/algebra/emulated/sw_bn254/g1.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/precomputations.go
  std/algebra/emulated/sw_bw6761/g1.go
  std/algebra/emulated/sw_bw6761/g2.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/precomputations.go
  std/algebra/interfaces.go
  std/algebra/native/sw_bls12377/g1_test.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls24315/g1_test.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/commitments/kzg/native_doc_test.go
  std/commitments/kzg/nonnative_doc_test.go
  std/commitments/kzg/verifier.go
  std/commitments/kzg/verifier_test.go
  std/math/emulated/emparams/emparams.go
  std/math/emulated/field_test.go
  std/recursion/groth16/native_doc_test.go
  std/recursion/groth16/nonnative_doc_test.go
  std/recursion/groth16/verifier.go
  std/recursion/groth16/verifier_test.go
  std/recursion/wrapped_hash_test.go
Labels: consolidate, zk-evm

#916 fix: use platform independent method for counting new multiplication overflow from result limb count
  std/math/emulated/field_ops.go
  std/math/emulated/hints.go
Labels: bug, P2: Medium

#915 feat: cache lookup blueprint entries in solving phase
  constraint/bls12-377/system.go
  constraint/bls12-381/system.go
  constraint/bls24-315/system.go
  constraint/bls24-317/system.go
  constraint/blueprint.go
  constraint/blueprint_logderivlookup.go
  constraint/bn254/system.go
  constraint/bw6-633/system.go
  constraint/bw6-761/system.go
  constraint/tinyfield/system.go
  internal/generator/backend/template/representations/system.go.tmpl
  test/engine.go
Labels: perf

#931 Perf: optimize addition chains in BW6-761 final exponentiation
  std/algebra/emulated/fields_bw6761/e6.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
Labels: perf

#880 feat: add PLONK in-circuit verifier
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/native/sw_bls12377/g1_test.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls24315/g1_test.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/commitments/kzg/verifier.go
  std/recursion/plonk/doc.go
  std/recursion/plonk/native_doc_test.go
  std/recursion/plonk/nonnative_doc_test.go
  std/recursion/plonk/opts.go
  std/recursion/plonk/verifier.go
  std/recursion/plonk/verifier_test.go
  std/recursion/wrapped_hash.go
  std/recursion/wrapped_hash_test.go
Labels: new feature, zk-evm, P1: High

#930 perf: use G2 precomputed lines for Miller loop
  backend/plonk/bls12-377/marshal.go
  backend/plonk/bls12-381/marshal.go
  backend/plonk/bls24-315/marshal.go
  backend/plonk/bls24-317/marshal.go
  backend/plonk/bn254/marshal.go
  backend/plonk/bw6-633/marshal.go
  backend/plonk/bw6-761/marshal.go
  go.mod
  go.sum
  internal/generator/backend/template/zkpschemes/plonk/plonk.marshal.go.tmpl
  std/algebra/emulated/sw_bw6761/g2.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/pairing_test.go
  std/algebra/emulated/sw_bw6761/precomputations.go
  std/commitments/kzg/verifier.go
  std/commitments/kzg/verifier_test.go
  std/recursion/groth16/verifier.go
  std/recursion/groth16/verifier_test.go
Labels: perf, zk-evm, P1: High

#934 perf: bounded scalar multiplication
  std/algebra/algopts/algopts.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/interfaces.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/commitments/kzg/verifier.go
  std/recursion/wrapped_hash.go
Labels: consolidate, zk-evm, P1: High
