Repository Consensys/gnark, pull requests merged in 2023-09, with the labels that each got.

#530 feat: add bounded comparator functions
  std/hints.go
  std/math/bits/conversion.go
  std/math/cmp/bounded.go
  std/math/cmp/bounded_test.go
  std/math/cmp/doc_isless_test.go
  std/math/cmp/generic.go
  std/math/cmp/generic_test.go
Labels: proposition

#835 fix: assert that the binary decomposition of a variable is less than the modulus
  frontend/api.go
  frontend/cs/r1cs/api.go
  frontend/cs/r1cs/api_assertions.go
  frontend/cs/scs/api.go
  frontend/cs/scs/api_assertions.go
  internal/backend/circuits/hint.go
  internal/regression_tests/doc.go
  internal/regression_tests/issue_836_test.go
  internal/stats/latest.stats
  std/math/bits/conversion.go
  std/math/bits/conversion_binary.go
  std/math/bits/intf_constcheck.go
  test/engine.go
Labels: bug, P1: High

#841 test: update version tag
  doc.go
Labels: bug
