Repository Consensys/gnark, pull requests merged in 2023-01, with the labels that each got.

#401 feat: keccak-f permutation function
  std/permutation/keccakf/keccak_test.go
  std/permutation/keccakf/keccakf.go
  std/permutation/keccakf/keccakf_native_test.go
  std/permutation/keccakf/uint64api.go
  std/permutation/keccakf/uint64api_test.go
Labels: new feature

#427 feat: adds `api.MAC(..)`
  frontend/api.go
  frontend/builder.go
  frontend/cs/r1cs/api.go
  frontend/cs/r1cs/api_assertions.go
  frontend/cs/r1cs/builder.go
  frontend/cs/scs/api.go
  std/math/emulated/field_assert.go
  std/math/emulated/wrapped_api.go
  test/engine.go
Labels: consolidate, perf

#438 fix: add shortcut for const input in MulConst
  std/math/emulated/field_ops.go
Labels: bug

#372 feat: add ECDSA signature verification
  go.mod
  go.sum
  std/algebra/weierstrass/doc.go
  std/algebra/weierstrass/doc_test.go
  std/algebra/weierstrass/params.go
  std/algebra/weierstrass/point.go
  std/algebra/weierstrass/point_test.go
  std/signature/ecdsa/ecdsa.go
  std/signature/ecdsa/ecdsa_test.go
Labels: new feature

#439 fix: pack full limbs for quotient
  std/math/emulated/element_test.go
  std/math/emulated/field.go
  std/math/emulated/field_assert.go
  std/math/emulated/field_ops.go
  std/math/emulated/hints.go
  std/math/emulated/wrapped_builder.go
Labels: bug

#446 feat: add automatic non-native witness element limb constraining
  frontend/internal/expr/linear_expression.go
  frontend/internal/expr/linear_expression_scs_torefactor.go
  internal/stats/latest.stats
  std/math/emulated/element.go
  std/math/emulated/element_test.go
  std/math/emulated/field.go
  std/math/emulated/field_assert.go
  std/math/emulated/field_binary.go
  std/math/emulated/field_ops.go
  std/math/emulated/wrapped_api.go
Labels: new feature
