Repository Consensys/gnark, pull requests merged in 2024-10, with the labels that each got.

#1282 added sudoku example for prover and verifier
  examples/sudoku/doc.go
  examples/sudoku/sudoku_example_test.go
Labels: good first issue, doc

#1289 chore: lint generated files
  .github/workflows/pr.yml
  .github/workflows/push.yml
  .golangci.yml
Labels: cleanup

#1288 fix: fix slice init length
  profile/internal/graph/graph.go
Labels: bug

#1293 fix: allow only v=0 or v=1
  std/evmprecompiles/01-ecrecover.go
  std/evmprecompiles/01-ecrecover_test.go
Labels: bug

#1295 chore: Pedersen verification key reference field
  backend/groth16/bls12-377/marshal_test.go
  backend/groth16/bls12-381/marshal_test.go
  backend/groth16/bls24-315/marshal_test.go
  backend/groth16/bls24-317/marshal_test.go
  backend/groth16/bn254/marshal_test.go
  backend/groth16/bn254/solidity.go
  backend/groth16/bw6-633/marshal_test.go
  backend/groth16/bw6-761/marshal_test.go
  go.mod
  go.sum
  internal/generator/backend/template/zkpschemes/groth16/tests/groth16.marshal.go.tmpl
  internal/tinyfield/element_test.go
  internal/tinyfield/vector.go
  std/commitments/pedersen/assignment.go
  std/commitments/pedersen/verifier.go
Labels: cleanup

#1294 fix: expmod precompile if modulus is 1
  std/evmprecompiles/05-expmod.go
  std/evmprecompiles/05-expmod_test.go
Labels: bug

#1296 Feat: 4-dimensional fake GLV
  internal/stats/latest_stats.csv
  std/algebra/emulated/sw_emulated/hints.go
  std/algebra/emulated/sw_emulated/params.go
  std/algebra/emulated/sw_emulated/params_compute.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls12377/g1_test.go
  std/algebra/native/sw_bls12377/hints.go
  std/algebra/native/sw_bls24315/g1.go
  std/algebra/native/twistededwards/curve.go
  std/algebra/native/twistededwards/curve_test.go
  std/algebra/native/twistededwards/hints.go
  std/algebra/native/twistededwards/point.go
  std/algebra/native/twistededwards/scalarmul_glv.go
  std/math/emulated/emparams/emparams.go
  std/math/emulated/params.go
Labels: new feature, perf
