Repository Consensys/gnark, pull requests merged in 2024-07, with the labels that each got.

#1173 perf(bls12-381): eliminate finalexp ~naively
  std/algebra/emulated/fields_bls12381/e12.go
  std/algebra/emulated/fields_bls12381/e12_pairing.go
  std/algebra/emulated/fields_bls12381/hints.go
  std/algebra/emulated/sw_bls12381/pairing.go
Labels: perf

#1187 fix: groth16 solidity templates
  backend/groth16/bls12-377/verify.go
  backend/groth16/bls12-381/verify.go
  backend/groth16/bls24-315/verify.go
  backend/groth16/bls24-317/verify.go
  backend/groth16/bn254/solidity.go
  backend/groth16/bn254/verify.go
  backend/groth16/bw6-633/verify.go
  backend/groth16/bw6-761/verify.go
  backend/groth16/groth16.go
  backend/plonk/plonk.go
  backend/solidity/solidity.go
  backend/solidity/verifyingkey.go
  internal/generator/backend/template/imports.go.tmpl
  internal/generator/backend/template/zkpschemes/groth16/groth16.verify.go.tmpl
  test/assert_checkcircuit.go
  test/assert_options.go
  test/assert_solidity.go
Labels: bug

#1197 feat: use blake2 for variable hashcode
  frontend/cs/r1cs/builder.go
  frontend/internal/expr/linear_expression.go
  frontend/internal/expr/term.go
  std/math/emulated/field.go
Labels: consolidate, perf

#1198 docs: describe potential length extension attack when using MiMC in-circuit
  std/hash/mimc/doc.go
  std/hash/mimc/mimc.go
  std/recursion/wrapped_hash.go
Labels: cleanup, doc

#1204 feat: add IsOnG2 for BN254
  std/algebra/emulated/fields_bn254/e2.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
Labels: consolidate

#1211 feat: capture O variable in gate for external range checker
  frontend/cs/scs/builder.go
Labels: consolidate, zk-evm

#1167 fix: use emulated arithmetic for GLV decomp
  std/algebra/native/sw_bls24315/g1.go
  std/algebra/native/sw_bls24315/g2.go
  std/algebra/native/sw_bls24315/hints.go
  std/algebra/native/sw_bls24315/pairing2.go
Labels: bug

#1212 fix: use consecutive powers instead of squaring
  std/multicommit/nativecommit.go
Labels: bug

#1145 fix: conditional check in non-native IsZero for applying optimization
  internal/stats/latest.stats
  std/math/emulated/field_assert.go
Labels: bug

#1214 fix: avoid malicious hint in BN254 final exp check
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/sw_bn254/hints.go
  std/algebra/emulated/sw_bn254/pairing.go
Labels: bug, zk-evm, P1: High

#1209 feat: add BN254 final exponentiation check with output
  std/algebra/emulated/fields_bn254/e12.go
  std/algebra/emulated/fields_bn254/e6.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
  std/evmprecompiles/08-bnpairing.go
Labels: consolidate

#1218 fix: remove unconstrained and unused variables
  std/algebra/emulated/sw_bn254/hints.go
  std/algebra/emulated/sw_bn254/pairing.go
Labels: bug

#1217 refactor: separate the fixed circuits for ECPairing used in zkevm
  std/evmprecompiles/08-bnpairing.go
Labels: consolidate, zk-evm, P1: High

#1200 fix: variable modulus subtraction padding
  std/math/emulated/custommod.go
  std/math/emulated/hints.go
Labels: bug

#1224 fix: strict ModReduce in emulated fields
  std/algebra/algopts/algopts.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/interfaces.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/math/emulated/element.go
  std/math/emulated/element_test.go
  std/math/emulated/field_assert.go
  std/math/emulated/field_binary.go
  std/math/emulated/field_ops.go
  std/math/emulated/field_reduce.go
Labels: consolidate, doc

#1226 fix: edge case with PLONK backend when 1 constraint
  std/math/emulated/element_test.go
Labels: bug

#1228 fixes #1227: api.AssertIsLessOrEqual incorrect behavior on R1CS with constant variable
  frontend/cs/r1cs/api_assertions.go
  frontend/cs/r1cs/builder.go
  internal/regression_tests/issue1227/issue_1227_test.go
Labels: fuzzing

#1207 perf: optimize class equivalence check for BLS12 final exp
  std/algebra/emulated/fields_bls12381/e12_pairing.go
  std/algebra/emulated/fields_bls12381/hints.go
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/pairing_test.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/pairing_test.go
  std/algebra/native/fields_bls12377/e12_pairing.go
  std/algebra/native/fields_bls12377/hints.go
  std/algebra/native/sw_bls12377/pairing.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls12377/pairing_test.go
Labels: perf, zk-evm

#1229 fix: minimum 1 bit for constant binary decomposition
  frontend/cs/r1cs/api_assertions.go
  internal/regression_tests/issue1227/issue_1227_test.go
Labels: fuzzing
