Repository Consensys/gnark, pull requests merged in 2024-02, with the labels that each got.

#1035 fix: use G1 generator from SRS
  std/commitments/kzg/verifier.go
Labels: bug

#1036 fix: another occurence of G1 in SRS
  std/commitments/kzg/verifier.go
Labels: bug

#1043 fix: organize std packages hints registrations
  std/algebra/native/fields_bls12377/e12.go
  std/algebra/native/fields_bls12377/e2.go
  std/algebra/native/fields_bls12377/e6.go
  std/algebra/native/fields_bls12377/hints.go
  std/algebra/native/fields_bls24315/e12.go
  std/algebra/native/fields_bls24315/e2.go
  std/algebra/native/fields_bls24315/e24.go
  std/algebra/native/fields_bls24315/e4.go
  std/algebra/native/fields_bls24315/hints.go
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls12377/g2.go
  std/algebra/native/sw_bls12377/hints.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls24315/g1.go
  std/algebra/native/sw_bls24315/g2.go
  std/algebra/native/sw_bls24315/hints.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/hints.go
Labels: bug

#1049 perf(sw_emulated): optimize jointScalarMulGeneric
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
Labels: perf

#1030 feat: subgroup G1/G2 membership BW6-761 and BLS12-377
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bw6761/doc_test.go
  std/algebra/emulated/sw_bw6761/g1.go
  std/algebra/emulated/sw_bw6761/g2.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/pairing_test.go
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls12377/g2.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls12377/pairing_test.go
Labels: new feature

#1053 chore: remove committed profiles
  profile001.pdf
  profile002.pdf
Labels: cleanup

#1054 feat: stabilize anonymous hint function names
  constraint/solver/hint.go
  constraint/solver/hint_registry.go
  constraint/solver/hint_test.go
  internal/regression_tests/issue1045/issue_1045_test.go
  internal/regression_tests/issue1045/testdata/issue1045.r1cs
  internal/regression_tests/issue1045/testdata/issue1045.scs
Labels: bug

#1052 feat: add option for enforcing number of goroutines for the solver
  constraint/bls12-377/solver.go
  constraint/bls12-381/solver.go
  constraint/bls24-315/solver.go
  constraint/bls24-317/solver.go
  constraint/bn254/solver.go
  constraint/bw6-633/solver.go
  constraint/bw6-761/solver.go
  constraint/solver/options.go
  constraint/tinyfield/solver.go
  internal/generator/backend/template/representations/solver.go.tmpl
  internal/regression_tests/issue1048/issue1048_test.go
Labels: consolidate

#1042 feat: non-native sumcheck verifier
  backend/groth16/bls12-377/prove.go
  backend/groth16/bls12-381/prove.go
  backend/groth16/bls24-315/prove.go
  backend/groth16/bls24-317/prove.go
  backend/groth16/bn254/prove.go
  backend/groth16/bw6-633/prove.go
  backend/groth16/bw6-761/prove.go
  backend/plonk/bls12-377/prove.go
  backend/plonk/bls12-381/prove.go
  backend/plonk/bls24-315/prove.go
  backend/plonk/bls24-317/prove.go
  backend/plonk/bn254/prove.go
  backend/plonk/bw6-633/prove.go
  backend/plonk/bw6-761/prove.go
  constraint/bls12-377/solver.go
  constraint/bls12-381/solver.go
  constraint/bls24-315/solver.go
  constraint/bls24-317/solver.go
  constraint/bn254/solver.go
  constraint/bw6-633/solver.go
  constraint/bw6-761/solver.go
  internal/generator/backend/main.go
  internal/generator/backend/template/representations/solver.go.tmpl
  internal/generator/backend/template/zkpschemes/groth16/groth16.prove.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/plonk.prove.go.tmpl
  std/math/polynomial/doc.go
  std/math/polynomial/polynomial.go
  std/math/polynomial/polynomial_test.go
  std/recursion/sumcheck/arithengine.go
  std/recursion/sumcheck/challenge.go
  std/recursion/sumcheck/claim_intf.go
  std/recursion/sumcheck/claimable_gate.go
  std/recursion/sumcheck/claimable_multilinear.go
  std/recursion/sumcheck/doc.go
  std/recursion/sumcheck/polynomial.go
  std/recursion/sumcheck/proof.go
  std/recursion/sumcheck/prover.go
  std/recursion/sumcheck/scalarmul_gates_test.go
  std/recursion/sumcheck/sumcheck_test.go
  std/recursion/sumcheck/verifier.go
Labels: new feature, consolidate
