Repository Consensys/gnark, pull requests merged in 2024-12, with the labels that each got.

#1333 perf: normalize the random linear combination in logderivarg
  std/internal/logderivarg/logderivarg.go
Labels: consolidate

#1331 perf: using non-native Eval for curve arithmetic
  internal/stats/latest_stats.csv
  std/algebra/emulated/fields_bw6761/e6.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/sw_bw6761/g1.go
  std/algebra/emulated/sw_bw6761/g2.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_emulated/point.go
  std/math/emulated/field_mul.go
Labels: perf, zk-evm

#1335 Pairing check optimisation
  std/algebra/emulated/fields_bls12381/e12_pairing.go
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/native/fields_bls12377/e12_pairing.go
Labels: consolidate

#1120 feat: add ripemd160 hash function with permutation
  std/hash/ripemd160/ripemd160.go
  std/hash/ripemd160/ripemd160_test.go
  std/math/uints/hints.go
  std/math/uints/uint8.go
  std/permutation/ripemd160/ripemd160block.go
  std/permutation/ripemd160/ripemd160block_native_test.go
  std/permutation/ripemd160/ripemd160block_test.go
Labels: new feature, zk-evm, P1: High

#1342 doc: add audit report
  README.md
  audits/2024-11 - Least Authority - Linea zkEVM.pdf
Labels: doc

#1337 chore: fix error message
  std/evmprecompiles/hints.go
Labels: typo

#1340 fix: NNA quotient length computation edge cases
  std/math/emulated/field_mul.go
Labels: bug

#1339 Perf: Pairing on BN254 using direct Fp12 extension and non-native `Eval()`
  internal/stats/latest_stats.csv
  std/algebra/emulated/fields_bn254/doc.go
  std/algebra/emulated/fields_bn254/e12.go
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/fields_bn254/e12_test.go
  std/algebra/emulated/fields_bn254/e2.go
  std/algebra/emulated/fields_bn254/e6.go
  std/algebra/emulated/fields_bn254/e6_test.go
  std/algebra/emulated/fields_bn254/hints.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/hints.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
  std/algebra/emulated/sw_emulated/point.go
  std/evmprecompiles/08-bnpairing.go
Labels: perf, zk-evm

#1349 feat(bls12-381): pairing using direct Fp12 + non-native `Eval()`
  internal/stats/latest_stats.csv
  std/algebra/emulated/fields_bls12381/doc.go
  std/algebra/emulated/fields_bls12381/e12.go
  std/algebra/emulated/fields_bls12381/e12_pairing.go
  std/algebra/emulated/fields_bls12381/e12_test.go
  std/algebra/emulated/fields_bls12381/e2.go
  std/algebra/emulated/fields_bls12381/e6.go
  std/algebra/emulated/fields_bls12381/e6_test.go
  std/algebra/emulated/fields_bls12381/hints.go
  std/algebra/emulated/sw_bls12381/hints.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/pairing_test.go
Labels: consolidate, perf

#1355 chore: remove duplicate nil-check
  std/algebra/emulated/sw_bls12381/pairing.go
Labels: cleanup

#1352 fix: avoid linking icicle dependent files when tag not provided
  README.md
  backend/groth16/bn254/icicle/device.go
  backend/groth16/bn254/icicle/doc.go
  backend/groth16/bn254/icicle/icicle.go
  backend/groth16/bn254/icicle/marshal_test.go
  backend/groth16/bn254/icicle/noicicle.go
  backend/groth16/bn254/icicle/provingkey.go
  backend/groth16/groth16.go
  go.mod
  go.sum
Labels: bug, consolidate

#1356 perf: G1/2 membership using Eval
  std/algebra/emulated/sw_bls12381/g1.go
  std/algebra/emulated/sw_bls12381/g2.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bw6761/g1.go
  std/algebra/emulated/sw_emulated/point.go
Labels: consolidate, perf

#1353 refactor: move poseidon2 to permutation package
  std/permutation/poseidon2/poseidon2.go
  std/permutation/poseidon2/poseidon2_test.go
Labels: consolidate

#1358 fix: tinyfield generation with updated gnark-crypto
  go.mod
  go.sum
  internal/generator/backend/main.go
  internal/tinyfield/arith.go
  internal/tinyfield/doc.go
  internal/tinyfield/element.go
  internal/tinyfield/element_purego.go
  internal/tinyfield/element_test.go
  internal/tinyfield/vector.go
  internal/tinyfield/vector_purego.go
  internal/tinyfield/vector_test.go
Labels: dependencies

#1345 Feat: settable hasher for MiMC
  std/hash/hash.go
  std/hash/mimc/mimc.go
  std/hash/mimc/mimc_test.go
Labels: new feature

#1359 fix: spellchecker
  std/math/emulated/emparams/emparams.go
  std/math/emulated/field_assert.go
  std/permutation/poseidon2/poseidon2.go
Labels: typo
