Repository Consensys/gnark, pull requests merged in 2024-04, with the labels that each got.

#1086 feat: add secp256k1 curve default initializer
  std/algebra/defaults.go
  std/algebra/emulated/sw_emulated/point.go
Labels: consolidate

#1087 perf: non-native multilinear polynomial evaluation
  std/math/polynomial/polynomial.go
  std/math/polynomial/polynomial_oldeval_test.go
  std/math/polynomial/polynomial_test.go
  std/recursion/sumcheck/claimable_gate.go
  std/recursion/sumcheck/claimable_multilinear.go
Labels: perf

#1090 feat: expmod with variable modulus
  std/evmprecompiles/05-expmod.go
  std/evmprecompiles/05-expmod_test.go
  std/evmprecompiles/doc.go
  std/math/emulated/composition.go
  std/math/emulated/composition_test.go
  std/math/emulated/custommod.go
  std/math/emulated/custommod_test.go
  std/math/emulated/doc.go
  std/math/emulated/element_test.go
  std/math/emulated/emparams/emparams.go
  std/math/emulated/field_assert.go
  std/math/emulated/field_mul.go
  std/math/emulated/field_ops.go
  std/math/emulated/hints.go
Labels: consolidate

#1109 docs: update TODOs
  backend/groth16/bn254/solidity.go
  frontend/cs/scs/builder.go
  frontend/schema/walk.go
  profile/profile_worker.go
  std/commitments/kzg/verifier.go
  std/math/emulated/composition.go
  std/recursion/plonk/verifier.go
  std/signature/ecdsa/ecdsa.go
Labels: cleanup

#1101 feat: handle invalid signature failures in ECRecover precompile
  go.mod
  go.sum
  std/evmprecompiles/01-ecrecover.go
  std/evmprecompiles/01-ecrecover_test.go
  std/evmprecompiles/hints.go
Labels: new feature, zk-evm, P1: High

#1113 docs: update documentation for ecdsa and eddsa
  std/signature/ecdsa/doc.go
  std/signature/ecdsa/ecdsa.go
  std/signature/eddsa/doc.go
  std/signature/eddsa/eddsa.go
Labels: doc

#1118 Update README.md
  README.md
Labels: cleanup, doc

#1111 refactor: remove todos
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls24315/g1.go
Labels: cleanup
