Repository Consensys/gnark, pull requests merged in 2024-09, with the labels that each got.

#1254 perf(bn254): optimize Miller loop
  internal/stats/latest.stats
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/precomputations.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/precomputations.go
Labels: perf, zk-evm

#1266 chore: explicit IO methods in interfaces
  backend/groth16/groth16.go
  backend/plonk/plonk.go
Labels: consolidate, doc

#1255 docs: update README
  CHANGELOG.md
  README.md
  audits/2022-10 - Kudelski - gnark-crypto.pdf
  audits/2024-05 - Sigma Prime - kzg.pdf
  audits/2024-05 - zksecurity - gnark std.pdf
  audits/2024-07 - Least Authority - arithm and GKR.pdf
  docs/CITATION.bib
  docs/KNOWN_USERS.md
Labels: doc

#1102 feat: allow configurable hash-to-field function for Groth16 Solidity verifier
  backend/groth16/bn254/solidity.go
  backend/groth16/bn254/verify.go
  backend/plonk/bn254/verify.go
  backend/solidity/solidity.go
  backend/solidity/solidity_test.go
  internal/generator/backend/template/zkpschemes/groth16/groth16.verify.go.tmpl
  internal/generator/backend/template/zkpschemes/plonk/plonk.verify.go.tmpl
  test/assert_checkcircuit.go
  test/assert_solidity.go
Labels: consolidate, P3: Low

#1274 chore: up gnark-crypto
  go.mod
  go.sum
  std/recursion/wrapped_hash.go
Labels: bug, cleanup

#1275 test: add scalar mul to stats
  internal/stats/latest.stats
  internal/stats/snippet.go
Labels: consolidate

#1283 docs: final audit report from LA
  README.md
  audits/2024-07 - Least Authority - arithm and GKR.pdf
  audits/2024-09 - Least Authority - arithm and GKR.pdf
Labels: doc
