Repository Consensys/gnark, pull requests merged in 2024-06, with the labels that each got.

#1139 fix(uints): constrain valueOf
  std/math/uints/uint8.go
  std/math/uints/uint8_test.go
Labels: bug, consolidate, P1: High

#1182 Make ExpMod work with parametric fields parameters
  std/evmprecompiles/05-expmod.go
  std/math/emulated/emparams/emparams.go
Labels: new feature, zk-evm

#1165 fix(math/bitslice): fix partition upper part range check width
  std/math/bitslice/opts.go
  std/math/bitslice/partition.go
  std/math/bitslice/partition_test.go
Labels: consolidate, doc
