Repository Consensys/gnark, pull requests merged in 2024-08, with the labels that each got.

#1234 fix: branch with unchecked cast could panic at compile time
  frontend/cs/scs/api_assertions.go
Labels: fuzzing

#1245 feat add random mask to groth16 commitment
  constraint/solver/hint_registry.go
  frontend/cs/r1cs/api.go
  internal/hints/hints.go
  internal/security_tests/advisory-9xcg/advisory_test.go
  internal/stats/latest.stats
  std/multicommit/nativecommit_test.go
Labels: bug

#1257 refactor: use strings.ReplaceAll
  profile/internal/graph/dotgraph.go
  profile/profile_worker.go
Labels: typo

#1240 chore: fix some function names
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/hash/mimc/encrypt.go
Labels: typo

#1185 fix: fix most typos
  backend/plonk/bls12-377/prove.go
  backend/plonk/bls12-381/prove.go
  backend/plonk/bls24-315/prove.go
  backend/plonk/bls24-317/prove.go
  backend/plonk/bn254/prove.go
  backend/plonk/bw6-633/prove.go
  backend/plonk/bw6-761/prove.go
  constraint/solver/hint.go
  constraint/solver/hint_test.go
  examples/rollup/error.go
  frontend/api.go
  frontend/compile.go
  frontend/cs/r1cs/r1cs_test.go
  internal/generator/backend/template/zkpschemes/plonk/plonk.prove.go.tmpl
  profile/internal/measurement/measurement.go
  profile/internal/report/report.go
  std/algebra/emulated/sw_bls12381/g1.go
  std/algebra/emulated/sw_bls12381/g2.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bn254/g1.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bw6761/g1.go
  std/algebra/emulated/sw_bw6761/g2.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/native/twistededwards/curve_test.go
  std/gkr/compile.go
  std/hash/hash.go
  std/math/cmp/bounded.go
  std/math/emulated/emparams/emparams.go
  std/math/emulated/field_mul.go
  std/multicommit/nativecommit.go
  std/recursion/groth16/nonnative_doc_test.go
  std/recursion/plonk/nonnative_doc_test.go
  std/recursion/plonk/verifier.go
Labels: typo

#1261 fix: several external typo fixes
  backend/plonk/bls12-377/prove.go
  backend/plonk/bls12-381/prove.go
  backend/plonk/bls24-315/prove.go
  backend/plonk/bls24-317/prove.go
  backend/plonk/bn254/prove.go
  backend/plonk/bw6-633/prove.go
  backend/plonk/bw6-761/prove.go
  constraint/solver/hint.go
  constraint/solver/hint_test.go
  examples/rollup/error.go
  frontend/api.go
  frontend/compile.go
  frontend/cs/r1cs/r1cs_test.go
  internal/generator/backend/template/zkpschemes/plonk/plonk.prove.go.tmpl
  profile/internal/graph/dotgraph.go
  profile/internal/measurement/measurement.go
  profile/internal/report/report.go
  profile/profile_worker.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/sw_bls12381/g1.go
  std/algebra/emulated/sw_bls12381/g2.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bn254/g1.go
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bw6761/g1.go
  std/algebra/emulated/sw_bw6761/g2.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/algebra/native/twistededwards/curve_test.go
  std/gkr/compile.go
  std/hash/hash.go
  std/hash/mimc/encrypt.go
  std/math/cmp/bounded.go
  std/math/emulated/emparams/emparams.go
  std/math/emulated/field_mul.go
  std/multicommit/nativecommit.go
  std/recursion/groth16/nonnative_doc_test.go
  std/recursion/plonk/nonnative_doc_test.go
  std/recursion/plonk/verifier.go
Labels: typo
