Repository Consensys/gnark, pull requests merged in 2024-11, with the labels that each got.

#1311 docs: add input packing example
  examples/inputpacking/doc.go
  examples/inputpacking/inputpacking_test.go
Labels: doc

#1317 fix: initialize public committed
  std/recursion/groth16/verifier.go
Labels: bug

#1299 feat: direct multivariate polynomial evaluation in non-native
  std/math/emulated/doc.go
  std/math/emulated/element_test.go
  std/math/emulated/field.go
  std/math/emulated/field_mul.go
  std/math/emulated/hints.go
Labels: perf

#1326 perf: fast path operations for small non-native values
  internal/stats/latest_stats.csv
  std/internal/limbcomposition/composition.go
  std/math/emulated/custommod.go
  std/math/emulated/element.go
  std/math/emulated/element_test.go
  std/math/emulated/emparams/emparams.go
  std/math/emulated/field.go
  std/math/emulated/field_mul.go
  std/math/emulated/field_ops.go
  std/math/emulated/params.go
  std/math/emulated/subtraction_padding.go
Labels: consolidate

#1312 perf: BW6 pairing computation using non-native Eval
  internal/stats/latest_stats.csv
  std/algebra/emulated/fields_bw6761/e6.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/fields_bw6761/e6_test.go
Labels: perf

#1324 fix bn254 solidity template
  backend/groth16/bn254/solidity.go
Labels: bug
