Repository Consensys/gnark, pull requests merged in 2024-05, with the labels that each got.

#1123 test: add PLONK test for public input mapping
  std/recursion/plonk/verifier_test.go
Labels: zk-evm

#1124 perf,feat: groth16.ProvingKey implements BinaryDumper using gnark-crypto unsafe
  backend/groth16/bls12-377/marshal.go
  backend/groth16/bls12-377/marshal_test.go
  backend/groth16/bls12-381/marshal.go
  backend/groth16/bls12-381/marshal_test.go
  backend/groth16/bls24-315/marshal.go
  backend/groth16/bls24-315/marshal_test.go
  backend/groth16/bls24-317/marshal.go
  backend/groth16/bls24-317/marshal_test.go
  backend/groth16/bn254/marshal.go
  backend/groth16/bn254/marshal_test.go
  backend/groth16/bw6-633/marshal.go
  backend/groth16/bw6-633/marshal_test.go
  backend/groth16/bw6-761/marshal.go
  backend/groth16/bw6-761/marshal_test.go
  backend/groth16/groth16.go
  go.mod
  go.sum
  internal/generator/backend/template/zkpschemes/groth16/groth16.marshal.go.tmpl
  internal/generator/backend/template/zkpschemes/groth16/tests/groth16.marshal.go.tmpl
  io/io.go
  io/roundtrip.go
Labels: new feature, perf

#1110 Perf: revisiting field extensions in `std/`
  internal/stats/latest.stats
  std/algebra/emulated/fields_bls12381/e12.go
  std/algebra/emulated/fields_bls12381/e12_pairing.go
  std/algebra/emulated/fields_bls12381/e2.go
  std/algebra/emulated/fields_bls12381/e6.go
  std/algebra/emulated/fields_bn254/e12.go
  std/algebra/emulated/fields_bn254/e12_pairing.go
  std/algebra/emulated/fields_bn254/e2.go
  std/algebra/emulated/fields_bn254/e6.go
  std/algebra/emulated/fields_bw6761/e3.go
  std/algebra/emulated/fields_bw6761/e6.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/fields_bw6761/hints.go
  std/algebra/emulated/sw_bls12381/pairing.go
Labels: perf, zk-evm

#1126 perf: direct Fp6 extension for BW6-761
  internal/stats/latest.stats
  std/algebra/emulated/fields_bw6761/e3.go
  std/algebra/emulated/fields_bw6761/e3_test.go
  std/algebra/emulated/fields_bw6761/e6.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/fields_bw6761/e6_test.go
  std/algebra/emulated/fields_bw6761/hints.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/native/fields_bls12377/e12.go
  std/algebra/native/fields_bls12377/e2.go
  std/algebra/native/fields_bls12377/e6.go
Labels: perf, zk-evm

#1128 fix: shift constraint indices by nb of public vars
  frontend/cs/scs/builder.go
Labels: bug, zk-evm, P1: High

#1104 fix: non-native arithmetic with variable modulus various fixes
  std/math/emulated/composition.go
Labels: bug

#1140 test: check KZG batch verify returned error in test circuit
  std/commitments/kzg/verifier_test.go
Labels: consolidate
