Repository Consensys/gnark, pull requests merged in 2024-01, with the labels that each got.

#993 feat: some todos and dead code
  std/algebra/emulated/sw_bls12381/g1.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/precomputations.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/native/fields_bls12377/e12.go
  std/algebra/native/fields_bls12377/e12_test.go
  std/algebra/native/fields_bls12377/e2_test.go
  std/algebra/native/fields_bls12377/e6_test.go
Labels: cleanup, perf

#976 perf(ecmul): use GLV with safe handling of edge cases in EVM ecmul
  std/algebra/algopts/algopts.go
  std/algebra/emulated/sw_emulated/hints.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/interfaces.go
  std/evmprecompiles/07-bnmul.go
Labels: perf, zk-evm, P2: Medium

#1008 fix: remove shorthash override for same field
  std/recursion/plonk/verifier_test.go
  std/recursion/wrapped_hash.go
Labels: bug

#1010 feat: different PLONK circuit verification
  std/recursion/plonk/doc.go
  std/recursion/plonk/verifier.go
  std/recursion/plonk/verifier_test.go
Labels: consolidate

#1016 perf: groth16 verifier circuit uses precomputed lines for all curves
  std/recursion/groth16/verifier.go
Labels: consolidate, perf

#1017 feat: use n-bit mux for switching PLONK verification keys
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/interfaces.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls12377/pairing2_test.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/algebra/native/sw_bls24315/pairing2_test.go
  std/math/emulated/element_test.go
  std/math/emulated/field_ops.go
  std/recursion/plonk/verifier.go
  std/recursion/plonk/verifier_test.go
Labels: consolidate

#1023 Fix: edge cases in `std/algebra` elliptic curve arithmetic circuit (`emulated` and `2-chains)`
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls12377/g1_test.go
  std/algebra/native/sw_bls12377/g2.go
  std/algebra/native/sw_bls12377/g2_test.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls24315/g1.go
  std/algebra/native/sw_bls24315/g1_test.go
  std/algebra/native/sw_bls24315/g2.go
  std/algebra/native/sw_bls24315/g2_test.go
  std/recursion/plonk/verifier.go
  std/recursion/plonk/verifier_test.go
Labels: bug, consolidate

#1026 fix: use subtraction with reduce in AssertIsEqual
  std/math/emulated/field_assert.go
  std/math/emulated/regression_test.go
Labels: bug
