Repository Consensys/gnark, pull requests merged in 2024-03, with the labels that each got.

#1068 fix: scs add/mul when recorded constraint is 0
  frontend/cs/scs/api.go
  frontend/cs/scs/api_test.go
Labels: bug

#1064 perf: emulated equality assertion
  internal/stats/latest.stats
  std/math/emulated/doc.go
  std/math/emulated/element_test.go
  std/math/emulated/field.go
  std/math/emulated/field_assert.go
  std/math/emulated/field_mul.go
  std/math/emulated/field_ops.go
  std/math/emulated/hints.go
Labels: perf

#1076 Faster cubic 01 01 mul
  internal/stats/latest.stats
  std/algebra/emulated/fields_bn254/e6.go
  std/algebra/emulated/fields_bn254/e6_test.go
  std/algebra/emulated/fields_bw6761/e3.go
  std/algebra/emulated/fields_bw6761/e3_test.go
  std/algebra/native/fields_bls12377/e6.go
  std/algebra/native/fields_bls12377/e6_test.go
Labels: perf

#1077 Faster cubic 012 mul 01
  internal/stats/latest.stats
  std/algebra/emulated/fields_bls12381/e6.go
  std/algebra/emulated/fields_bn254/e6.go
  std/algebra/emulated/fields_bw6761/e3.go
  std/algebra/native/fields_bls12377/e6.go
  std/algebra/native/fields_bls12377/e6_test.go
  std/algebra/native/fields_bls24315/e12.go
  std/algebra/native/fields_bls24315/e12_test.go
Labels: perf

#1080 feat: add hint calling with either native inputs or outputs
  std/math/emulated/field_hint.go
  std/math/emulated/field_test.go
Labels: new feature

#1083 fix: emulated hint tests
  std/math/emulated/field_test.go
Labels: bug

#1061 Perf: optimize EC arithmetic
  frontend/cs/scs/api.go
  internal/stats/latest.stats
  std/algebra/emulated/sw_emulated/hints.go
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/emulated/sw_emulated/point_test.go
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls12377/g2.go
  std/algebra/native/sw_bls12377/inner.go
  std/algebra/native/sw_bls24315/g1.go
  std/algebra/native/sw_bls24315/g2.go
  std/algebra/native/sw_bls24315/inner.go
  std/commitments/kzg/verifier.go
  std/evmprecompiles/01-ecrecover.go
Labels: perf, zk-evm

#1072 feat: add MulNoReduce and Sum methods in field emulation
  std/math/emulated/element_test.go
  std/math/emulated/field_mul.go
  std/math/emulated/field_ops.go
Labels: new feature

#1085 Perf: optimize scalar multiplication for 2-chains
  internal/stats/latest.stats
  std/algebra/emulated/sw_emulated/point.go
  std/algebra/native/fields_bls12377/e12_pairing.go
  std/algebra/native/fields_bls12377/e2.go
  std/algebra/native/sw_bls12377/g1.go
  std/algebra/native/sw_bls12377/g2.go
  std/algebra/native/sw_bls12377/hints.go
  std/algebra/native/sw_bls12377/pairing.go
  std/algebra/native/sw_bls12377/pairing2.go
  std/algebra/native/sw_bls24315/g1.go
  std/algebra/native/sw_bls24315/g1_test.go
  std/algebra/native/sw_bls24315/g2.go
  std/algebra/native/sw_bls24315/hints.go
  std/algebra/native/sw_bls24315/pairing2.go
  std/commitments/kzg/verifier.go
  std/math/emulated/emparams/emparams.go
Labels: perf, zk-evm

#1089 perf/fix: assume variable as zero constant when subtracting from itself
  frontend/cs/r1cs/api_assertions.go
  frontend/cs/r1cs/builder.go
  frontend/cs/r1cs/r1cs_test.go
  frontend/cs/scs/api_test.go
  frontend/cs/scs/builder.go
Labels: bug, perf

#1066 feat: add range check selector retrieval
  frontend/cs/scs/builder.go
Labels: consolidate
