Repository Consensys/gnark, pull requests merged in 2025-09, with the labels that each got.

#1605 Handle empty inputs in EvalUnivariate and EvalMultilinearMany
  std/math/polynomial/polynomial.go
Labels: src: community

#1597 plonk(recursion): fix incorrect error messages for bw6-761 and bn254 branches
  std/recursion/plonk/verifier.go
Labels: src: community

#1588 fix: propagate ReadFrom errors in generated r1cs tests
  constraint/babybear/r1cs_test.go
  constraint/bls12-377/r1cs_test.go
  constraint/bls12-381/r1cs_test.go
  constraint/bls24-315/r1cs_test.go
  constraint/bls24-317/r1cs_test.go
  constraint/bn254/r1cs_test.go
  constraint/bw6-633/r1cs_test.go
  constraint/bw6-761/r1cs_test.go
  constraint/koalabear/r1cs_test.go
  constraint/tinyfield/r1cs_test.go
  internal/generator/backend/template/representations/tests/r1cs.go.tmpl
Labels: src: community

#1604 perf(bls12-381/map-to-g1): use triple in mul by seed
  std/algebra/emulated/sw_bls12381/g1.go
  std/algebra/emulated/sw_bls12381/g1_test.go
  std/algebra/emulated/sw_bls12381/map_to_g1.go
Labels: type: perf

#1572 feat: pointeval precompile circuit for failing inputs
  internal/security_tests/advisory-9xcg/advisory_test.go
  std/algebra/algopts/algopts.go
  std/algebra/emulated/sw_bls12381/hints.go
  std/algebra/emulated/sw_bls12381/marshal.go
  std/algebra/emulated/sw_bls12381/marshal_test.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/evmprecompiles/10-kzg_point_evaluation.go
  std/evmprecompiles/10-kzg_point_evaluation_test.go
  std/evmprecompiles/doc.go
Labels: type: new feature
