Repository Consensys/gnark, pull requests merged in 2025-01, with the labels that each got.

#1385 fix: do not return unused sign
  internal/stats/latest_stats.csv
  std/algebra/emulated/sw_emulated/hints.go
  std/algebra/emulated/sw_emulated/point.go
Labels: bug, consolidate

#1386 perf(emulated): small perf on doubleAndAdd
  internal/stats/latest_stats.csv
  std/algebra/emulated/sw_emulated/point.go
Labels: perf, zk-evm

#1387 perf(bn254): include G2 membership check in ML
  internal/stats/latest_stats.csv
  std/algebra/emulated/sw_bn254/g2.go
  std/algebra/emulated/sw_bn254/g2_test.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/precomputations.go
  std/evmprecompiles/08-bnpairing.go
Labels: perf, zk-evm

#1374 fix typos
  examples/rollup/circuit.go
  examples/rollup/operator.go
Labels: typo

#1390 refactor: use maps.Clone to simplify the code and reorder packages
  constraint/solver/hint_registry.go
Labels: typo

#1392 chore: remove redundant word in comment
  std/algebra/emulated/sw_bn254/pairing.go
Labels: typo

#1396 refactor: use strings.Cut
  frontend/schema/tags.go
Labels: typo

#1365 perf: `PairingCheck` for BN254, BLS12-381, BLS12-377 and BW6-761
  go.mod
  go.sum
  internal/tinyfield/element.go
  std/algebra/emulated/fields_bw6761/e6_pairing.go
  std/algebra/emulated/fields_bw6761/hints.go
  std/algebra/emulated/sw_bls12381/hints.go
  std/algebra/emulated/sw_bls12381/pairing.go
  std/algebra/emulated/sw_bls12381/pairing_test.go
  std/algebra/emulated/sw_bn254/hints.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/algebra/emulated/sw_bn254/pairing_test.go
  std/algebra/emulated/sw_bw6761/hints.go
  std/algebra/emulated/sw_bw6761/pairing.go
  std/algebra/emulated/sw_bw6761/pairing_test.go
  std/algebra/emulated/sw_bw6761/precomputations.go
  std/algebra/native/sw_bls12377/hints.go
  std/algebra/native/sw_bls12377/pairing.go
  std/algebra/native/sw_bls12377/pairing2.go
Labels: perf

#1397 fix: add G2 membership check for constant points
  std/algebra/emulated/sw_bn254/g2.go
Labels: consolidate

#1398 fix: stashed typo fixes for v0.12
  constraint/solver/hint_registry.go
  examples/rollup/circuit.go
  examples/rollup/operator.go
  frontend/schema/tags.go
  std/algebra/emulated/sw_bn254/pairing.go
  std/polynomial/polynomial.go
Labels: typo
